name: dionysius
title: Dionysius
summary: Top-down shooter
version: '0.0.1'
grade: devel
base: core18
grade: devel
confinement: devmode
adopt-info: dionysius
parts: 
  dionysius:
    plugin: maven
    source: https://github.com/karl-zschiebsch/dionysius.git
    source-type: git
    source-tag: master
    maven-options: [install]
    stage-packages: [openjdk-11-jre-headless]
    parse-info: [https://github.com/karl-zschiebsch/dionysius/blob/master/dionysius.metainfo.xml]
